### ISSUE TITLE
It is not downloading anything ....

### ISSUE THREAD

**Issue by chiragdkothari** [Jacotsu/polibeepsync#51]
i successfully logged in and it retrieved the data of my courses but it isnt downloading anything i tries several times .... i have attached a gif of trying sync now button ..... nothing is being downloaded ... i am i doing something wrong?
![pBS](https://user-images.githubusercontent.com/7547555/79071567-c4863300-7cdc-11ea-827f-9d5d64870b16.gif)

**Comment by Jacotsu** [comment]
I can't reproduce this on my machine, maybe beep's server where busy when you tried to sync.
Have you tried to reinstall after deleting the internal data (just delete `%appdata%\..\Local\polibeepsync`)?

**Comment by chiragdkothari** [comment]
Sorry but ... i am still geting the same thing ..... i will try it on another system aznd get back to you thanks ....

**Comment by Jacotsu** [comment]
> Sorry but ... i am still geting the same thing ..... i will try it on another system aznd get back to you thanks ....

I've managed to reproduce the issue thanks to another bug report.
Basically BeeP's servers are too slow to respond to polibeepsync, so the program assumes that they're offline.

I'll release the next patch in a few days

**Comment by chiragdkothari** [comment]
still getting the same thing ,,,, my internet speed is around 25Mbps ... first i thought the network was causing the problem but i tried with couple of other networks and VPN too... is there any other way to run the code on windows ,,, like using CMD ?

**Comment by Jacotsu** [comment]
> still getting the same thing ,,,, my internet speed is around 25Mbps ... first i thought the network was causing the problem but i tried with couple of other networks and VPN too... is there any other way to run the code on windows ,,, like using CMD ?

First make sure that you're using Polibeepsync version 0.7.1, if it doesn't work you can use different timeouts settings by following this procedure:
- open a `cmd` or `powershell` terminal
- go to polibeepsync's download folder (version 0.7.1 doesn't require installation)
- type `.\polibeepsync.exe --default-timeout 20 --log-level debug`
The debug info will be printed on the console in the status tab

**Comment by chiragdkothari** [comment]
I tried it .... didnt work for 20 but when i made the timeout to 200 i think i recognised that sync is required and tried to do it  but then no files got downloaded ... here is a image for ref ,,,, 
![image](https://user-images.githubusercontent.com/7547555/79548340-9b2b2580-8095-11ea-9696-b677ed702e9f.png)

**Comment by Jacotsu** [comment]
> I tried it .... didnt work for 20 but when i made the timeout to 200 i think i recognised that sync is required and tried to do it but then no files got downloaded ... here is a image for ref ,,,,
> ![image](https://user-images.githubusercontent.com/7547555/79548340-9b2b2580-8095-11ea-9696-b677ed702e9f.png)

Make sure that you've checked which courses you want to sync

![Screenshot from 2020-04-17 22:36:25](https://user-images.githubusercontent.com/20172693/79612090-45d62f00-80fc-11ea-91bf-cf6723196d77.png)

**Comment by chiragdkothari** [comment]
yes ... i had marked the courses Machine Design 2 and Measurements for syncing thats why in last section of the status it said syncing these to courses but didnt download the files ...
![image](https://user-images.githubusercontent.com/7547555/79642863-31e40900-81a0-11ea-821d-5a9d42056f11.png)

 is it possible that there is another timeout that is being triggered here?

**Comment by Jacotsu** [comment]
> yes ... i had marked the courses Machine Design 2 and Measurements for syncing thats why in last section of the status it said syncing these to courses but didnt download the files ...
> ![image](https://user-images.githubusercontent.com/7547555/79642863-31e40900-81a0-11ea-821d-5a9d42056f11.png)
> 
> is it possible that there is another timeout that is being triggered here?

The timeout is set globally when you specify that option.

Can you send me your data file? it should be located in `%AppData%\..\Local\poliBeePsync\poliBeePsync\pbs.data`.
You can use telegram (@jacotsu) or email dcdrj.pub AT gmail DOT com

**Comment by Jacotsu** [comment]
> yes ... i had marked the courses Machine Design 2 and Measurements for syncing thats why in last section of the status it said syncing these to courses but didnt download the files ...
> ![image](https://user-images.githubusercontent.com/7547555/79642863-31e40900-81a0-11ea-821d-5a9d42056f11.png)
> 
> is it possible that there is another timeout that is being triggered here?

I've inspected the data file that you've sent me. You were right, i forgot to override the file download timeout so it was still waiting for 10 seconds instead of your set value.
I've pushed the fix in the master branch and will release the patch in a few days.

PS: If i were You, I would also check your internet connection. response times higher that 10 seconds are not normal (unless you have some exotic setup)

**Comment by Jacotsu** [comment]
I've released the fixed version, please download it and let me know if you still have problems

**Comment by chiragdkothari** [comment]
sorry but i am still getting the same thing as before ... i deleted the data file and started fresh with the new update ... i have the latest data file in the mail ....

**Comment by Jacotsu** [comment]
> sorry but i am still getting the same thing as before ... i deleted the data file and started fresh with the new update ... i have the latest data file in the mail ....

are you starting the program with `.\polibeepsync.exe --default-timeout 200 --log-level debug` or by double clicking? Because if you double click the default timeout will be 10

**Comment by chiragdkothari** [comment]
I started using the cmd command .....
